travis:
  secure:
    BINSTAR_TOKEN: foTnK5BBuDGpPs0IVnZFrG4DOtMl1YZsMC3I19+hR6YyOpa+e900V/eIvefsPFRNxMECTY1U38dmXcYiU43xEiwC1kumAarHjaA681p6PTnnqx00l4qBuSGFnkh1jCQc+moTusYxWdCAWuy6uUNIdfqRmu3w2kR6+oKw5sD05eEasX8wSKkl8amMvxIWWIXVYbR0lF/3poqUZgVS4IpD+4TyzUi/6EhmsILG8C8QJDZ9UasApn+6YtsrhTxU1kW7KhTMgLRbhzWLBCrncMjahOjlyZdGrFRDj9vfevv11ukpFKVger0EIKmrY0HbNRkNoxZA9Ycc5VnyTNNRLBh/BhKo1PgUbGOS1q9P6gGFQ1b4PFJgMydQjOSVTYB8WQYK8rRn6xllqJX79jm2aePyVanDROruXl2qHIQ2RWYZ4qa1vN0oxYVuH6oQTNSYjDnGWRiKBtAmlabrzsVI9cG0sn7uXMNldo8gdZNa2bkZRY894zSWBQOPuDSrm6lfb6AlbK8R37idVsb9qjtc0rw7MfERdlY2xqfvP3OKnmytudi3l0UROldYrM+EXB8F7af/WpfKZXSruXLrZvhI3/dYAIyaHg3DnLlJz/3uPXkprIh6BJsNjFOQ7kuNnbBbipJ2/9S02m+HU59c440NzQua06g5djw8LS7WXJR1jhAr4zo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
