appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DlF2awXSo3JHCgRw+prh09CK5ogq3GRlK/QPnB1/6f4/oaoZ8ywelBDhzmTJ+5S9Hbg/dDyY9PqAeo/JbEfetgH2ZdPOvhANpxgYmn22aKi/m+d2D8ENOpwuMO8BqmBCW7x9TEOz+Mhck/v77Q3suhoLk5t+piZVx4VFCRYR6nbc9A/Ojnb/lnenv0DM2rZzEqs0cHYCZXldaz0XkD83+CTwitxElr6L68fweWTtqOxruMopCpnEwrTVZdm0ZxBLrp8k5RXTlmXGxtjJEK2cZ8eHpekbFUIxtwC2coPXx9Ej4pNN+6TdH1KYbRUdn0lv0eNimgRgriHYHJW8J3rinivJCyM5TCfD0C6TZ1zEbzFuBbNA2oT91Lg6xvO8Xho+5ybA7Rk65MtTk6jBkRAZ0f/6mhGSdXzWDaPL37Bzp92MqpzDRgpRleXQ/Zirdh9Dii2zaNfVtXl2Lqlv0Ugxw8r24XkkgPKnA0xAm6Dka5ZgMybmfWQoaXSCXuiaT/2og4oBCHe15F7C50Nndm7haK6EJpCAkpr4xCnqtYcGsRJPzeJSizGjqFb1cwelj7ypUHzXLDiPOb7iljUoBiiDKx2wi4ElGbMttiwgZ4AhWokZmc2ncOerLXmsw6nfDC9F+/agurBX6xtXfxxondNJJj95ONoVwBHasgI5aWMsCcI=}
conda_forge_output_validation: true
